language: node_js
node_js:
  - "10"
cache:
  yarn: true
env:
  global:
    CC_TEST_REPORTER_ID=516f722ed278bfe45d9e1c63b2676f3991463303fd812cddd4eed5eba5aaa88e
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn install
  - yarn db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - echo "" >> .env
  - echo ./cc-test-reporter

script:
  - yarn test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


