version: '3'
services:
  web:
    build: .
    env_file:
      - ./.env
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db/dev_db'
    depends_on:
      - db
  db:
    image: postgres
    expose:
      - '5432'
    ports:
      - '5433:5432'

