version: "3"
services:
  api:
    build:
      context: .
    container_name: authentication-api
    command: npm run start:dev
    depends_on:
      - database
    ports: 
        - "8080:8080" 
    environment:
      DATABASE_URL: "postgres://postgres:postgres@database:5432/bdirs"
      PORT: 8080   
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bdirs
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"



